config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount RootApi => '/'
  mount Resque::Server.new, at: '/resque'
  post :toggle, to: 'locales#toggle'
  namespace :admin do
    root 'users#index'
    resources :users
  end
  devise_for :users
  resources :events
  get 'events/page/(:page(.:format))', to: 'events#index'
  get 'help', to: 'help#index', as: 'help_index'
  get 'about', to: 'about#index', as: 'about_index'
  scope '/:locale' do
    get 'about', to: 'about#index'
  end
  root 'events#index'
  
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { maximum: 20, minimum: 3 }
  after_save :count_events
  after_destroy :recount_events

  private

  def count_events
    user.increment!(done? ? :events_done_count : :events_not_done_count)
  end

  def recount_events
    user.decrement!(done? ? :events_done_count : :events_not_done_count)
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :event
  validates :name, presence: true
  validates :name, length: { maximum: 20, minimum: 3 }
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :users, dependent: :nullify
  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 3 }
  validates :name, uniqueness: true
  validates :code, presence: true
  validates :code, uniqueness: true
  validates :code, length: { maximum: 16, minimum: 3 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
  before_validation :set_role, on: %i[create update]
  belongs_to :role
  has_many :events, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true

  if defined?(Role) && ActiveRecord::Base.connection.table_exists?(:roles)
    Role.find_each do |role|
      define_method "#{role.code}?" do
        role_id == role.id
      end
    end
  end

  def admin?
    role&.code == 'admin'
  end

  before_save :ensure_authentication_token

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

  def normalize_email
    self.email = email&.downcase
  end

  def normalize_name
    self.name = name&.downcase&.titleize
  end

  def set_role
    self.role ||= Role.find_by(code: :default)
  end
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
def index
  session[:about_counter] ||= 0
  session[:about_counter] += 1
  I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ApplicationController
    layout 'layouts/admin/application'
    before_action :authenticate_user!
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_admin_user, only: %i[show edit update destroy]
    # after_action :verify_authorized, except: :index
    # after_action :verify_policy_scoped, only: :index
    # GET /admin/users
    def index
      authorize [:admin, User]
      @admin_users = policy_scope(User,
                                  policy_scope_class: Admin::UserPolicy::Scope)
                     .includes(:role).page(params[:page]).per(9)
    end

    # GET /admin/users/1
    def show; end

    # GET /admin/users/new
    def new
      authorize [:admin, User]
      @admin_user = User.new
    end

    # GET /admin/users/1/edit
    def edit; end

    # POST /admin/users
    def create
      @admin_user = User.new(admin_user_params)
      authorize [:admin, @admin_user]
      if @admin_user.save
        redirect_to [:admin, @admin_user], notice: 'User was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      authorize [:admin, @admin_user]
      if @admin_user.update(admin_user_params)
        redirect_to [:admin, @admin_user], notice: 'User was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/users/1
    def destroy
      authorize [:admin, @admin_user]
      @admin_user.destroy
      redirect_to admin_users_url, notice: 'User was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role_id)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :devise_permit_params, if: :devise_controller?
  before_action :check_locale

  private

  def check_locale
    I18n.locale = session[:locale] if I18n.available_locales.include? session[:locale]&.to_sym
  end

  def devise_permit_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /events
  def index
    @events = policy_scope(Event).includes(:items).page(params[:page]).per(6)
  end

  # GET /events/1
  def show
    authorize @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :content, :done)
  end
end

app/controllers/help_controller.rb
# frozen_string_literal: true

class HelpController < ApplicationController
  def index; end
end

app/controllers/locales_controller.rb
# frozen_string_literal: true

class LocalesController < ApplicationController
  def toggle
    session[:locale] ||= I18n.default_locale.to_s
    session[:locale] = (session[:locale] == 'ru' ? 'en' : 'ru')

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_date
    Date.current.to_s
  end

  def list_tag(arr)
    tag.ul do
      safe_join(arr.map { |line| raw tag.li(line) })
    end
  end
end

app/views/about/index.html.slim
h1
  = t(:about)
p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero repudiandae, est repellendus soluta consequatur officia quas quae nulla illo voluptate, omnis at&nbsp;a&nbsp;quisquam porro eaque neque unde error illum sit magnam obcaecati impedit inventore dolorem dolorum? Sapiente ipsum facilis debitis cumque aspernatur magni blanditiis veritatis reprehenderit commodi earum, quas ullam impedit, corrupti pariatur? Numquam reprehenderit, ab&nbsp;ratione hic, quibusdam adipisci quod dolore obcaecati aut incidunt, aliquam minus. Voluptates asperiores quis aliquam ipsa 
p
  = t(:current_date)
  =< l Date.current
p
  = t(:visits)
  =< session[:about_counter] 
p
  = list_tag(%w[first second third]) 
  = image_tag("tig.jpg", width: "700px")
p
  => link_to t(:main_page), root_path

p 
  = link_to t(:help), help_index_path
/ == render 'shared/language_files'

app/views/admin/users/_form.html.slim
= bootstrap_form_for [:admin, @admin_user] do |f|
  - if @admin_user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_user.errors.count, 'error')} prohibited this admin_user from being saved:"
      ul
        - @admin_user.errors.full_messages.each do |message|
          li = message

  = f.text_field :name
  = f.text_field :email
  - if @admin_user.id != current_user.id
    = f.collection_select :role_id, Role.order(:name), :id, :name
  - if action_name == 'new'
    = f.password_field :password
    = f.password_field :password_confirmation
  .actions = f.submit class: "btn btn-success"

app/views/admin/users/edit.html.slim
h1.text-info.text-center Editing admin_user

== render 'form'
br
=> link_to 'Show', [:admin, @admin_user], class: "btn btn-info"
'|
=< link_to 'Back', admin_users_path, class: "btn btn-secondary"

app/views/admin/users/index.html.slim
h1.text-info.text-center  Listing admin_users

table.table.table-dark.table-sm.table-striped 
  thead
    tr
      th Имя
      th Email
      th Роль
      th Просмотреть
      th Редактировать
      th Удалить
  tbody
    - @admin_users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.role.name
        td = link_to 'Show', admin_user_path(user), class: "btn btn-info"
        td = link_to 'Edit', edit_admin_user_path(user), class: "btn btn-warning"
        td = link_to 'Destroy', admin_user_path(user), data: { confirm: 'Are you sure?' }, method: :delete,
             class: "btn btn-danger"

br

p
  = link_to 'New User', new_admin_user_path, class: "btn btn-info"
p
  = paginate @admin_users, theme: 'bootstrap-5',
                           pagination_class: "pagination-sm flex-wrap justify-content-center",
                           nav_class: "d-inline-block"

app/views/admin/users/new.html.slim
h1.text-info.text-center New admin_user

== render 'form'
br
= link_to 'Back', admin_users_path, class: "btn btn-secondary"

app/views/admin/users/show.html.slim
p#notice = notice

=> link_to 'Edit', edit_admin_user_path(@admin_user)
'|
=< link_to 'Back', admin_users_path

app/views/events/_event.html.slim
tr
  td = event.items.size
  td = link_to event.name, event
  td = link_to 'Edit', edit_event_path(event), class: "btn btn-warning"

app/views/events/_form.html.slim
= bootstrap_form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, 'error')} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  = f.text_field :name
  = f.text_area :content
  = f.check_box :done
  .actions = f.submit class: "btn btn-success"

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

=> link_to t(:show), @event
'|
=< link_to t(:back), events_path

p
==< render 'shared/language_files'

app/views/events/index.html.slim
h1.text-info.text-center 
  = t(:events)
table.table.table-dark.table-sm.table-striped 
  thead
    tr
      th Подзадачи
      th Задача
      th Редактировать
  tbody
    = render partial: 'event', collection: @events
        
p
  = link_to t(:new_event), new_event_path, class: "btn btn-success"
p
  = paginate @events, theme: 'bootstrap-5',
                      pagination_class: "pagination-sm flex-wrap justify-content-center",
                      nav_class: "d-inline-block"

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p 
  strong Name: 
  =< @event.name
p 
  strong Content: 
  =< @event.content  
p 
  strong Done: 
  =< @event.done
p 
  strong Items:
  table 
    - @event.items.order(:created_at).each_with_index do |item, i|
      tr
        td = i + 1
        td = item.name

=> link_to 'Edit', edit_event_path(@event)
'|
=< link_to 'Back', events_path

app/views/help/index.html.slim
h1
  = t(:help)
p  Тут будет очень важная информация!

p
  = link_to t(:main), root_path

app/views/layouts/admin/application.html copy.slim
doctype html
html
  head
    title
      | TODO
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .wrapper
      = render 'shared/header'
      main.bg-dark
        
        = yield
      footer.bg-dark
        p &copy; All rights reserved
      
      / header
      /   nav
      /     ul.menu_list
      /       li.menu_list 
      /         = link_to_unless_current  t(:main), root_path, class: 'nav_link'
      /       li.menu_list 
      /         = link_to_unless_current  t(:help), help_index_path, class: 'nav_link'
      /       li.menu_list 
      /         = link_to_unless_current  t(:about), about_index_path, class: 'nav_link'
      /       li.menu-list 

app/views/layouts/admin/application.html.slim
doctype html
html
  head
    title
      | Система Администрирования
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .wrapper
      = render 'shared/header'
      main.bg-dark
        
        = yield
      footer.bg-dark
        p &copy; All rights reserved

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TODO
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    = favicon_link_tag asset_path('favicon.ico')
  body
    .wrapper
      
      = render 'shared/header'
      main.bg-dark
        
        = yield
      footer.bg-dark
        p &copy; All rights reserved
      
      

app/views/locales/toggle.html.slim
h1 Locales#toggle
p Find me in app/views/locales/toggle.html.slim

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-expand-sm.bg-dark.navbar-light.border-bottom.border-success
    .container-fluid.header_menu
      ul.navbar-nav
        li.nav-item
          = link_to_unless_current  t(:main), root_path, class: 'nav_link'
        li.nav-item
          = link_to_unless_current  t(:help), help_index_path, class: 'nav_link'
        li.nav-item
          = link_to_unless_current  t(:about), about_index_path, class: 'nav_link'
        
      ul.navbar-nav
        == render 'shared/language_files'
      ul.navbar-nav
        - if user_signed_in?
          li.nav-item
            span
              => t('label.hello') % current_user.name
              |(
              = link_to t('label.edit_profile'), edit_user_registration_path
              |)
          li.nav-item
            = link_to t('label.log_out'), destroy_user_session_path, method: :delete, class: 'nav_link'
        - else
          li.nav-item
            = link_to t('label.log_in'), new_user_session_path
          li.nav-item
           = link_to t('label.registration'), new_user_registration_path

 

app/views/shared/_language_files.html.slim
- link_name = session[:locale] == I18n.default_locale.to_s ? 'EN' : 'RU'
=< link_to link_name, toggle_path, method: :post